create type public.interaction_type as enum ('Meeting','Call','Message','Workshop','POC','Internal Collaboration','Other');
create type public.interaction_outcome as enum ('Positive','Neutral','Negative','Pending');
create type public.task_status as enum ('Open','In Progress','Completed','Cancelled');
create type public.insight_type as enum ('Sales Insight','Customer Insight','Technical Insight','Workplace Insight','Communication Insight','Leadership Insight','Personal Growth Insight');
create type public.insight_status as enum ('Proposed','Observed','Testing','Validated','Retired');
create type public.report_type as enum ('Daily','Weekly');

create table public.interactions(
 id uuid primary key default gen_random_uuid(), owner_id uuid not null default auth.uid() references auth.users(id),
 customer_id uuid not null, contact_id uuid, opportunity_id uuid, interaction_type public.interaction_type not null,
 occurred_at timestamptz not null, title text not null check(length(btrim(title)) between 1 and 300), summary text,
 notes text, outcome public.interaction_outcome not null default 'Pending', sales_impact text, follow_up_required boolean not null default false,
 participant_snapshot jsonb not null default '[]' check(jsonb_typeof(participant_snapshot)='array'),
 data_level public.data_level not null default 'Level3', classification_reason text,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),version integer not null default 1,
 deleted_at timestamptz,deleted_by uuid references auth.users(id),unique(owner_id,id),
 foreign key(owner_id,customer_id) references public.customers(owner_id,id),
 foreign key(owner_id,contact_id) references public.contacts(owner_id,id),
 foreign key(owner_id,opportunity_id) references public.opportunities(owner_id,id)
);

create table public.tasks(
 id uuid primary key default gen_random_uuid(),owner_id uuid not null default auth.uid() references auth.users(id),
 title text not null check(length(btrim(title)) between 1 and 300),description text,status public.task_status not null default 'Open',
 due_at timestamptz,estimated_effort_minutes integer check(estimated_effort_minutes is null or estimated_effort_minutes between 1 and 2880),
 customer_id uuid,contact_id uuid,opportunity_id uuid,interaction_id uuid,completed_at timestamptz,
 data_level public.data_level not null default 'Level2',classification_reason text,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),version integer not null default 1,
 deleted_at timestamptz,deleted_by uuid references auth.users(id),unique(owner_id,id),
 foreign key(owner_id,customer_id) references public.customers(owner_id,id),foreign key(owner_id,contact_id) references public.contacts(owner_id,id),
 foreign key(owner_id,opportunity_id) references public.opportunities(owner_id,id),foreign key(owner_id,interaction_id) references public.interactions(owner_id,id)
);
create table public.task_status_history(
 id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id),task_id uuid not null,
 from_status public.task_status,to_status public.task_status not null,changed_at timestamptz not null default now(),recorded_at timestamptz not null default clock_timestamp(),operation_id uuid not null,
 unique(owner_id,id),foreign key(owner_id,task_id) references public.tasks(owner_id,id)
);

create table public.insights(
 id uuid primary key default gen_random_uuid(),owner_id uuid not null default auth.uid() references auth.users(id),title text not null check(length(btrim(title)) between 1 and 300),
 insight_type public.insight_type not null,status public.insight_status not null default 'Proposed',summary text not null,content text,
 mastery smallint check(mastery between 1 and 5),interaction_id uuid,task_id uuid,opportunity_id uuid,learning_id uuid,knowledge_id uuid,
 data_level public.data_level not null default 'Level2',classification_reason text,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),version integer not null default 1,
 deleted_at timestamptz,deleted_by uuid references auth.users(id),unique(owner_id,id),
 foreign key(owner_id,interaction_id) references public.interactions(owner_id,id),foreign key(owner_id,task_id) references public.tasks(owner_id,id),
 foreign key(owner_id,opportunity_id) references public.opportunities(owner_id,id),foreign key(owner_id,learning_id) references public.learning(owner_id,id),
 foreign key(owner_id,knowledge_id) references public.knowledge(owner_id,id),
 check(num_nonnulls(interaction_id,task_id,opportunity_id,learning_id,knowledge_id)>=1)
);

create table public.reports(
 id uuid primary key default gen_random_uuid(),owner_id uuid not null default auth.uid() references auth.users(id),report_type public.report_type not null,
 report_date date,period_start timestamptz,period_end timestamptz,timezone text not null default 'Asia/Shanghai',
 focus text,reflection text,risks text,next_plan text,as_of timestamptz not null default now(),
 data_level public.data_level not null default 'Level2',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),version integer not null default 1,
 deleted_at timestamptz,deleted_by uuid references auth.users(id),unique(owner_id,id),
 check((report_type='Daily' and report_date is not null and period_start is null and period_end is null) or (report_type='Weekly' and report_date is null and period_start is not null and period_end is not null and period_end>period_start))
);
create unique index reports_daily_unique on public.reports(owner_id,report_date,timezone) where deleted_at is null and report_type='Daily';
create unique index reports_weekly_unique on public.reports(owner_id,period_start,period_end,timezone) where deleted_at is null and report_type='Weekly';

create trigger interactions_guard before update on public.interactions for each row execute function public.guard_mutable_entity();
create trigger interactions_no_delete before delete on public.interactions for each row execute function public.reject_mutable_entity_delete();
create trigger tasks_guard before update on public.tasks for each row execute function public.guard_mutable_entity();
create trigger tasks_no_delete before delete on public.tasks for each row execute function public.reject_mutable_entity_delete();
create trigger insights_guard before update on public.insights for each row execute function public.guard_mutable_entity();
create trigger insights_no_delete before delete on public.insights for each row execute function public.reject_mutable_entity_delete();
create trigger reports_guard before update on public.reports for each row execute function public.guard_mutable_entity();
create trigger reports_no_delete before delete on public.reports for each row execute function public.reject_mutable_entity_delete();
create function private.reject_task_history_mutation() returns trigger language plpgsql set search_path='' as $$begin raise exception using errcode='P0001',message='task status history is append-only';end;$$;
create trigger task_history_append_only before update or delete on public.task_status_history for each row execute function private.reject_task_history_mutation();

do $$declare t text;begin foreach t in array array['interactions','tasks','task_status_history','insights','reports'] loop execute format('alter table public.%I enable row level security',t);execute format('alter table public.%I force row level security',t);execute format('create policy %I on public.%I for select to authenticated using(auth.uid()=owner_id%s)',t||'_owner_select',t,case when t in('interactions','tasks','insights','reports') then ' and deleted_at is null' else '' end);execute format('create policy %I on public.%I for all to authenticated using(false) with check(false)',t||'_browser_mutation_denied',t);end loop;end$$;
grant select,insert,update,delete on public.interactions,public.tasks,public.task_status_history,public.insights,public.reports to authenticated,service_role;

create function private.reassign_daily_customer_links(p_owner_id uuid,p_survivor_id uuid,p_duplicate_id uuid)returns jsonb language plpgsql security definer set search_path='' as $$declare interactions_moved integer;tasks_moved integer;begin update public.interactions set customer_id=p_survivor_id where owner_id=p_owner_id and customer_id=p_duplicate_id;get diagnostics interactions_moved=row_count;update public.tasks set customer_id=p_survivor_id where owner_id=p_owner_id and customer_id=p_duplicate_id;get diagnostics tasks_moved=row_count;return jsonb_build_object('interactionsReassigned',interactions_moved,'tasksReassigned',tasks_moved);end$$;
create function private.reassign_daily_contact_links(p_owner_id uuid,p_survivor_id uuid,p_duplicate_id uuid)returns jsonb language plpgsql security definer set search_path='' as $$declare interactions_moved integer;tasks_moved integer;begin update public.interactions set contact_id=p_survivor_id where owner_id=p_owner_id and contact_id=p_duplicate_id;get diagnostics interactions_moved=row_count;update public.tasks set contact_id=p_survivor_id where owner_id=p_owner_id and contact_id=p_duplicate_id;get diagnostics tasks_moved=row_count;return jsonb_build_object('interactionsReassigned',interactions_moved,'tasksReassigned',tasks_moved);end$$;
update private.merge_hook_manifests set expected_dependencies=array_cat(expected_dependencies,array['public.interactions.customer_id','public.tasks.customer_id'])where entity_type='Customer';
update private.merge_hook_manifests set expected_dependencies=array_cat(expected_dependencies,array['public.interactions.contact_id','public.tasks.contact_id'])where entity_type='Contact';
insert into private.merge_reassignment_hooks(entity_type,hook_name,function_name,execution_order,schema_version,covered_dependencies)values('Customer','daily_customer_links','private.reassign_daily_customer_links(uuid,uuid,uuid)'::regprocedure,30,1,array['public.interactions.customer_id','public.tasks.customer_id']),('Contact','daily_contact_links','private.reassign_daily_contact_links(uuid,uuid,uuid)'::regprocedure,30,1,array['public.interactions.contact_id','public.tasks.contact_id']);

create function private.refresh_daily_search(p_owner uuid,p_type text,p_id uuid) returns void language plpgsql security definer set search_path='' as $$declare title text;subtitle text;body text;route text;level public.data_level;created timestamptz;updated timestamptz;deleted timestamptz;begin
 if p_type='Interaction' then select i.title,i.interaction_type::text,concat_ws(E'\n',i.title,i.summary,i.notes,i.sales_impact),'/interactions/'||i.id,i.data_level,i.created_at,i.updated_at,i.deleted_at into title,subtitle,body,route,level,created,updated,deleted from public.interactions i where i.owner_id=p_owner and i.id=p_id;
 elsif p_type='Task' then select t.title,t.status::text,concat_ws(E'\n',t.title,t.description),'/tasks/'||t.id,t.data_level,t.created_at,t.updated_at,t.deleted_at into title,subtitle,body,route,level,created,updated,deleted from public.tasks t where t.owner_id=p_owner and t.id=p_id;
 elsif p_type='Insight' then select i.title,i.insight_type::text,concat_ws(E'\n',i.title,i.summary,i.content),'/insights/'||i.id,i.data_level,i.created_at,i.updated_at,i.deleted_at into title,subtitle,body,route,level,created,updated,deleted from public.insights i where i.owner_id=p_owner and i.id=p_id;end if;
 insert into public.search_documents(owner_id,source_type,source_id,title,subtitle,search_text,route,data_level,visibility_state,source_created_at,source_updated_at,projection_schema_version,indexed_at,metadata) values(p_owner,p_type,p_id,title,subtitle,body,route,level,case when deleted is null then 'Active' else 'Deleted' end,created,updated,1,now(),'{}') on conflict(owner_id,source_type,source_id)do update set title=excluded.title,subtitle=excluded.subtitle,search_text=excluded.search_text,visibility_state=excluded.visibility_state,source_updated_at=excluded.source_updated_at,indexed_at=excluded.indexed_at;
end$$;

create function public.create_interaction(p_verified_user_id uuid,p_client_request_id uuid,p_customer_id uuid,p_contact_id uuid,p_opportunity_id uuid,p_interaction_type public.interaction_type,p_occurred_at timestamptz,p_title text,p_summary text,p_notes text,p_outcome public.interaction_outcome,p_sales_impact text,p_follow_up_required boolean,p_participant_snapshot jsonb)
returns table(id uuid,version integer,operation_id uuid) language plpgsql security definer set search_path='' as $$declare r record;e public.interactions%rowtype;begin if auth.role()<>'service_role'then raise exception using errcode='42501',message='service role required';end if;select * into r from private.claim_command_receipt(p_verified_user_id,'CreateInteraction',p_client_request_id);if r.status='Completed'then return query select (r.result_reference->>'id')::uuid,1,r.operation_id;return;end if;insert into public.interactions(owner_id,customer_id,contact_id,opportunity_id,interaction_type,occurred_at,title,summary,notes,outcome,sales_impact,follow_up_required,participant_snapshot)values(p_verified_user_id,p_customer_id,p_contact_id,p_opportunity_id,p_interaction_type,p_occurred_at,btrim(p_title),p_summary,p_notes,p_outcome,p_sales_impact,p_follow_up_required,coalesce(p_participant_snapshot,'[]'))returning * into e;perform private.refresh_daily_search(p_verified_user_id,'Interaction',e.id);perform private.append_audit_log(p_verified_user_id,'InteractionCreated','Interaction',e.id,null,p_client_request_id,r.operation_id,'["title","occurred_at"]','{}',null,null,'Success',null);perform private.complete_command_receipt(p_verified_user_id,r.id,r.operation_id,'Completed','Interaction',e.id,jsonb_build_object('id',e.id));return query select e.id,e.version,r.operation_id;end$$;
create function public.create_task(p_verified_user_id uuid,p_client_request_id uuid,p_title text,p_description text,p_due_at timestamptz,p_estimated_effort_minutes integer,p_customer_id uuid,p_contact_id uuid,p_opportunity_id uuid,p_interaction_id uuid)
returns table(id uuid,version integer,operation_id uuid)language plpgsql security definer set search_path='' as $$declare r record;e public.tasks%rowtype;begin if auth.role()<>'service_role'then raise exception using errcode='42501',message='service role required';end if;select * into r from private.claim_command_receipt(p_verified_user_id,'CreateTask',p_client_request_id);if r.status='Completed'then return query select (r.result_reference->>'id')::uuid,1,r.operation_id;return;end if;insert into public.tasks(owner_id,title,description,due_at,estimated_effort_minutes,customer_id,contact_id,opportunity_id,interaction_id,data_level)values(p_verified_user_id,btrim(p_title),p_description,p_due_at,p_estimated_effort_minutes,p_customer_id,p_contact_id,p_opportunity_id,p_interaction_id,case when p_customer_id is not null or p_contact_id is not null or p_opportunity_id is not null or p_interaction_id is not null then 'Level3'::public.data_level else 'Level2'::public.data_level end)returning * into e;insert into public.task_status_history(owner_id,task_id,from_status,to_status,operation_id)values(p_verified_user_id,e.id,null,'Open',r.operation_id);perform private.refresh_daily_search(p_verified_user_id,'Task',e.id);perform private.append_audit_log(p_verified_user_id,'TaskCreated','Task',e.id,null,p_client_request_id,r.operation_id,'["title","due_at"]','{}',null,null,'Success',null);perform private.complete_command_receipt(p_verified_user_id,r.id,r.operation_id,'Completed','Task',e.id,jsonb_build_object('id',e.id));return query select e.id,e.version,r.operation_id;end$$;
create function public.change_task_status(p_verified_user_id uuid,p_client_request_id uuid,p_task_id uuid,p_expected_version integer,p_to_status public.task_status)returns table(id uuid,version integer,status public.task_status,operation_id uuid)language plpgsql security definer set search_path='' as $$declare r record;e public.tasks%rowtype;old public.task_status;begin if auth.role()<>'service_role'then raise exception using errcode='42501',message='service role required';end if;select * into r from private.claim_command_receipt(p_verified_user_id,'ChangeTaskStatus',p_client_request_id);if r.status='Completed'then return query select p_task_id,(r.result_reference->>'version')::int,(r.result_reference->>'status')::public.task_status,r.operation_id;return;end if;select * into e from public.tasks where owner_id=p_verified_user_id and tasks.id=p_task_id and deleted_at is null for update;if e.id is null then raise exception 'task not found';end if;if e.version<>p_expected_version then raise exception using errcode='40001',message='task version conflict';end if;old:=e.status;if old=p_to_status then raise exception 'status must change';end if;update public.tasks set status=p_to_status,completed_at=case when p_to_status='Completed'then now()else null end,updated_at=now()where owner_id=p_verified_user_id and tasks.id=p_task_id returning * into e;insert into public.task_status_history(owner_id,task_id,from_status,to_status,operation_id)values(p_verified_user_id,p_task_id,old,p_to_status,r.operation_id);perform private.refresh_daily_search(p_verified_user_id,'Task',e.id);perform private.append_audit_log(p_verified_user_id,'TaskStatusChanged','Task',e.id,null,p_client_request_id,r.operation_id,'["status"]',jsonb_build_object('from',old,'to',p_to_status),null,null,'Success',null);perform private.complete_command_receipt(p_verified_user_id,r.id,r.operation_id,'Completed','Task',e.id,jsonb_build_object('id',e.id,'version',e.version,'status',e.status));return query select e.id,e.version,e.status,r.operation_id;end$$;
create function public.create_insight(p_verified_user_id uuid,p_client_request_id uuid,p_title text,p_insight_type public.insight_type,p_summary text,p_content text,p_interaction_id uuid,p_task_id uuid,p_opportunity_id uuid,p_learning_id uuid,p_knowledge_id uuid)returns table(id uuid,version integer,operation_id uuid)language plpgsql security definer set search_path='' as $$declare r record;e public.insights%rowtype;begin if auth.role()<>'service_role'then raise exception using errcode='42501',message='service role required';end if;select * into r from private.claim_command_receipt(p_verified_user_id,'CreateInsight',p_client_request_id);if r.status='Completed'then return query select (r.result_reference->>'id')::uuid,1,r.operation_id;return;end if;insert into public.insights(owner_id,title,insight_type,summary,content,interaction_id,task_id,opportunity_id,learning_id,knowledge_id,data_level)values(p_verified_user_id,btrim(p_title),p_insight_type,p_summary,p_content,p_interaction_id,p_task_id,p_opportunity_id,p_learning_id,p_knowledge_id,case when p_interaction_id is not null or p_task_id is not null or p_opportunity_id is not null then 'Level3'::public.data_level else 'Level2'::public.data_level end)returning * into e;perform private.refresh_daily_search(p_verified_user_id,'Insight',e.id);perform private.append_audit_log(p_verified_user_id,'InsightCreated','Insight',e.id,null,p_client_request_id,r.operation_id,'["title","insight_type"]','{}',null,null,'Success',null);perform private.complete_command_receipt(p_verified_user_id,r.id,r.operation_id,'Completed','Insight',e.id,jsonb_build_object('id',e.id));return query select e.id,e.version,r.operation_id;end$$;
create function public.change_insight_status(p_verified_user_id uuid,p_client_request_id uuid,p_insight_id uuid,p_expected_version integer,p_status public.insight_status,p_mastery smallint)returns table(id uuid,version integer,status public.insight_status,operation_id uuid)language plpgsql security definer set search_path='' as $$declare r record;e public.insights%rowtype;begin if auth.role()<>'service_role'then raise exception using errcode='42501',message='service role required';end if;select * into r from private.claim_command_receipt(p_verified_user_id,'ChangeInsightStatus',p_client_request_id);if r.status='Completed'then return query select p_insight_id,(r.result_reference->>'version')::int,(r.result_reference->>'status')::public.insight_status,r.operation_id;return;end if;select * into e from public.insights where owner_id=p_verified_user_id and insights.id=p_insight_id and deleted_at is null for update;if e.id is null then raise exception 'insight not found';end if;if e.version<>p_expected_version then raise exception using errcode='40001',message='insight version conflict';end if;if p_status='Validated'and p_mastery is null then raise exception 'validated insight requires mastery evidence';end if;update public.insights set status=p_status,mastery=p_mastery,updated_at=now()where owner_id=p_verified_user_id and insights.id=p_insight_id returning * into e;perform private.refresh_daily_search(p_verified_user_id,'Insight',e.id);perform private.append_audit_log(p_verified_user_id,'InsightStatusChanged','Insight',e.id,null,p_client_request_id,r.operation_id,'["status","mastery"]',jsonb_build_object('status',e.status),null,null,'Success',null);perform private.complete_command_receipt(p_verified_user_id,r.id,r.operation_id,'Completed','Insight',e.id,jsonb_build_object('id',e.id,'version',e.version,'status',e.status));return query select e.id,e.version,e.status,r.operation_id;end$$;
create function public.save_report(p_verified_user_id uuid,p_client_request_id uuid,p_report_type public.report_type,p_report_date date,p_period_start timestamptz,p_period_end timestamptz,p_timezone text,p_focus text,p_reflection text,p_risks text,p_next_plan text)returns table(id uuid,version integer,operation_id uuid)language plpgsql security definer set search_path='' as $$declare r record;e public.reports%rowtype;begin if auth.role()<>'service_role'then raise exception using errcode='42501',message='service role required';end if;select * into r from private.claim_command_receipt(p_verified_user_id,'SaveReport',p_client_request_id);if r.status='Completed'then return query select (r.result_reference->>'id')::uuid,(r.result_reference->>'version')::int,r.operation_id;return;end if;
if p_report_type='Daily'then insert into public.reports(owner_id,report_type,report_date,period_start,period_end,timezone,focus,reflection,risks,next_plan)values(p_verified_user_id,p_report_type,p_report_date,null,null,p_timezone,p_focus,p_reflection,p_risks,p_next_plan)on conflict(owner_id,report_date,timezone)where deleted_at is null and report_type='Daily'do update set focus=excluded.focus,reflection=excluded.reflection,risks=excluded.risks,next_plan=excluded.next_plan,updated_at=now()returning * into e;
else insert into public.reports(owner_id,report_type,report_date,period_start,period_end,timezone,focus,reflection,risks,next_plan)values(p_verified_user_id,p_report_type,null,p_period_start,p_period_end,p_timezone,p_focus,p_reflection,p_risks,p_next_plan)on conflict(owner_id,period_start,period_end,timezone)where deleted_at is null and report_type='Weekly'do update set focus=excluded.focus,reflection=excluded.reflection,risks=excluded.risks,next_plan=excluded.next_plan,updated_at=now()returning * into e;end if;
perform private.append_audit_log(p_verified_user_id,'ReportSaved','Report',e.id,null,p_client_request_id,r.operation_id,'["focus","reflection","risks","next_plan"]',jsonb_build_object('reportType',p_report_type),null,null,'Success',null);perform private.complete_command_receipt(p_verified_user_id,r.id,r.operation_id,'Completed','Report',e.id,jsonb_build_object('id',e.id,'version',e.version));return query select e.id,e.version,r.operation_id;end$$;

revoke all on function public.create_interaction(uuid,uuid,uuid,uuid,uuid,public.interaction_type,timestamptz,text,text,text,public.interaction_outcome,text,boolean,jsonb)from public,anon,authenticated;
revoke all on function public.create_task(uuid,uuid,text,text,timestamptz,integer,uuid,uuid,uuid,uuid)from public,anon,authenticated;
revoke all on function public.change_task_status(uuid,uuid,uuid,integer,public.task_status)from public,anon,authenticated;
revoke all on function public.create_insight(uuid,uuid,text,public.insight_type,text,text,uuid,uuid,uuid,uuid,uuid)from public,anon,authenticated;
revoke all on function public.change_insight_status(uuid,uuid,uuid,integer,public.insight_status,smallint)from public,anon,authenticated;
revoke all on function public.save_report(uuid,uuid,public.report_type,date,timestamptz,timestamptz,text,text,text,text,text)from public,anon,authenticated;
grant execute on function public.create_interaction(uuid,uuid,uuid,uuid,uuid,public.interaction_type,timestamptz,text,text,text,public.interaction_outcome,text,boolean,jsonb)to service_role;
grant execute on function public.create_task(uuid,uuid,text,text,timestamptz,integer,uuid,uuid,uuid,uuid)to service_role;
grant execute on function public.change_task_status(uuid,uuid,uuid,integer,public.task_status)to service_role;
grant execute on function public.create_insight(uuid,uuid,text,public.insight_type,text,text,uuid,uuid,uuid,uuid,uuid)to service_role;
grant execute on function public.change_insight_status(uuid,uuid,uuid,integer,public.insight_status,smallint)to service_role;
grant execute on function public.save_report(uuid,uuid,public.report_type,date,timestamptz,timestamptz,text,text,text,text,text)to service_role;
